- defaults:
    link:
      relink: true
      force: true
      create: true

- clean: ['~']

- link:
    ~/.config/qutebrowser/config.py:
      path: .config/qutebrowser/config.py
    ~/.config/i3/config:
      path: .config/i3/config
    ~/.config/i3status/config:
      path: .config/i3status/config

- shell:
  - [git submodule update --init --recursive, Installing submodules]
