#!/usr/bin/env bash
#
# Single command installation with
#  ____        _   ____        _
# |  _ \  ___ | |_| __ )  ___ | |_
# | | | |/ _ \| __|  _ \ / _ \| __|
# | |_| | (_) | |_| |_) | (_) | |_
# |____/ \___/ \__|____/ \___/ \__|
#
# https://github.com/anishathalye/dotbot
#

set -e

CONFIG="conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
