#
#   __  __       _         _         __  __ _                   _
#  |  \/  | __ _| |__   __| |_   _  |  \/  (_)_ __ ______ _  __| | ___
#  | |\/| |/ _` | '_ \ / _` | | | | | |\/| | | '__|_  / _` |/ _` |/ _ \
#  | |  | | (_| | | | | (_| | |_| | | |  | | | |   / / (_| | (_| |  __/
#  |_|  |_|\__,_|_| |_|\__,_|\__, | |_|  |_|_|_|  /___\__,_|\__,_|\___|
#                            |___/
#
# This file is a part of `github.com/mahdymirzade/dotfiles`.
#
- clean: ['~']

- shell:
  - [sed -i "s/#greeter-session=example-gtk-gnome/greeter-session=lightdm-gtk-greeter/g" /etc/lightdm/lightdm.conf]
  - [rm -rf /usr/share/icons/Tela-circle-black /usr/share/themes/Nordic-darker]
  - [cp -rf ../themes/Tela-circle-black /usr/share/icons/]
  - [cp -rf ../themes/Nordic-darker /usr/share/themes/]
  - [cp -rf ../wallpaper/lockscreen.png /usr/share/pixmaps/lightdm.background.png]
  - [cp -rf lightdm-gtk-greeter.conf /etc/lightdm/lightdm-gtk-greeter.conf]
  - [git submodule update --init --recursive, Installing submodules]
