#
#   __  __       _         _         __  __ _                   _
#  |  \/  | __ _| |__   __| |_   _  |  \/  (_)_ __ ______ _  __| | ___
#  | |\/| |/ _` | '_ \ / _` | | | | | |\/| | | '__|_  / _` |/ _` |/ _ \
#  | |  | | (_| | | | | (_| | |_| | | |  | | | |   / / (_| | (_| |  __/
#  |_|  |_|\__,_|_| |_|\__,_|\__, | |_|  |_|_|_|  /___\__,_|\__,_|\___|
#                            |___/
#
# This file is a part of `github.com/mahdymirzade/dotfiles`.
#
- defaults:
    link:
      relink: true
      force: true
      create: true

- clean: ['~']

- link:
    ~/.config/i3/config:
      path: config
    ~/.config/i3status/config:
      path: ../i3status/config

- shell:
  - [git submodule update --init --recursive, Installing submodules]
