- defaults:
    link:
      relink: true
      force: true
      create: true

- clean: ['~']

- link:
    ~/.config/i3/config:
      path: config
    ~/.config/i3status/config:
      path: ../i3status/config

- shell:
  - [git submodule update --init --recursive, Installing submodules]
